/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_tasks"];
        put?: never;
        post: operations["create_task"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Request body for creating a task. Title-only: status defaults to `Todo` and the id /
         *     timestamps are server-minted, so the caller supplies just the title. The domain rule
         *     (trimmed, 1..=200, non-blank) is enforced by `Title::parse` in the use-case.
         */
        CreateTaskRequest: {
            title: string;
        };
        /**
         * @description Health payload. `status` is always `ok`; `time` is sourced through the `Clock` port,
         *     proving that seam is wired end to end.
         */
        HealthResponse: {
            /** @description Always `"ok"` when the service is live. */
            status: string;
            /** @description Server time (RFC3339). */
            time: string;
        };
        /**
         * @description Transport representation of a [`Task`]. Timestamps are RFC3339 strings so the shape is
         *     stable across the OpenAPI boundary (and the generated TypeScript client).
         */
        TaskDto: {
            /** @description RFC3339 creation timestamp. */
            createdAt: string;
            /** @description uuidv7 identifier. */
            id: string;
            /** @description Owner (Auth0 subject). */
            owner: string;
            status: components["schemas"]["TaskStatusDto"];
            title: string;
            /** @description RFC3339 last-update timestamp. */
            updatedAt: string;
        };
        /**
         * @description Transport representation of [`TaskStatus`].
         * @enum {string}
         */
        TaskStatusDto: "todo" | "inProgress" | "done";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is live */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_tasks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's tasks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDto"][];
                };
            };
        };
    };
    create_task: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskRequest"];
            };
        };
        responses: {
            /** @description The created task */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDto"];
                };
            };
            /** @description Invalid or malformed request body (bad title, malformed JSON, or schema mismatch) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description Unsupported media type (expected application/json) */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
}
